spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    # mysql8 以下
    # url： jdbc:mysql://localhost:3306/mybatis_plus?characterEncoding=utf-8&useSSL=false
    # mysql8 以上
    url: jdbc:mysql://localhost:3306/mybatis?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  servlet:
    multipart:
      # 单个文件上传大小限制 10MB
      max-file-size: 20MB
      # 单个请求中文件上传最大限制 100MB(一个请求中可以上传多个文件)
      max-request-size: 100MB

# mybatis-plus log
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 开启驼峰命名 mybatis-plus 已经自动开启
    # map-underscore-to-camel-case: true

  # 设置 识别 xml文件的位置 ， 以下为默认路径
 # mapper-locations: classpath:/mapper/**/*.xml
  # 配置实体类的包路径  设置类型别名
 # type-aliases-package: com.javastudy.mybatisplus.pojo
  # 扫描通用枚举的包
 # type-enums-package: com.javastudy.mybatisplus.enums


  # 设置全局配置
  global-config:
    db-config:
      # 设置实体类所对应表的同一前缀
      # table-prefix: tb_
      # 设置同一的主键生成策略
      id-type: auto

